[General]
network = AdvancedRingNetwork
sim-time-limit = 1s
[Config AdvancedRing_STM16]

*.adm*.stmLevel = 16
**.numTributaries = 2
*.adm*.allowMixedInsertion = true
*.source*.packetSize = 300
*.source*.packetInterval = 30us

# Visualización
*.visualizer.*.enabled = true
*.visualizer.*.displayRoutes = false
*.visualizer.*.displayPacketDrops = true
*.visualizer.*.displayLabels = true
*.visualizer.*.animationSpeed = 20



# STM niveles y tributarios
**.stmLevel = 1

**.scalar-recording = true
**.vector-recording = true
**.stmForwarded.record = vector
**.pdhReceived.record = vector
**.pdhTransmitted.record = vector

