[General]
network = SimpleRingNetwork
sim-time-limit = 1s

[Config SimpleRing_STM4]

*.adm*.stmLevel = 4
**.packetSize = 1000
**.packetInterval = 100us
**.numTributaries = 1

# Visualización
*.visualizer.*.enabled = true
*.visualizer.*.animationSpeed = 20
*.visualizer.*.displayRoutes = false
*.visualizer.*.displayLabels = true
*.visualizer.*.displayPacketDrops = true

# Escenario
*.lteSource.stmLevel = 1
*.lteSink.stmLevel = 1
*.lteSource.useProtection = false
*.lteSink.useProtection = false


*.source.packetInterval = 20us
*.source.packetSize = 150

# Tiempos de animación
*.lteSource.protectionSwitchTime = -1s
*.lteSink.protectionSwitchTime = -1s

# Registro de estadísticas (opcional)
**.scalar-recording = true
**.vector-recording = true
**.stmForwarded.record = vector
**.pdhReceived.record = vector
**.pdhTransmitted.record = vector