[General]
network = p2pNetwork
sim-time-limit = 1s


[STM1]

*.lteA.stmLevel = 1
*.lteB.stmLevel = 1
*.lteA.numTributaries = 1
*.lteB.numTributaries = 1
**.packetSize= 2430
**.packetInterval = 41.62 us

[STM4]

*.lteA.stmLevel = 1
*.lteB.stmLevel = 1
*.lteA.numTributaries = 1
*.lteB.numTributaries = 1
**.packetSize= 9720
**.packetInterval = 41.62 us

[STM16]

*.lteA.stmLevel = 1
*.lteB.stmLevel = 1
*.lteA.numTributaries = 1
*.lteB.numTributaries = 1
**.packetSize= 38880
**.packetInterval = 41.62 us

# Visualization and animation
*.visualizer.*.enabled = true
*.visualizer.*.animationSpeed = 20
*.visualizer.*.displayRoutes = false
*.visualizer.*.displayPacketDrops = true
*.visualizer.*.displayLabels = true

# Disable recording
**.scalar-recording = true
**.vector-recording = true


# Traffic generation
*.sourceA.packetInterval = 50us
*.sourceA.packetSize = 3000 # in bytes


[Protection]
*.lteA.useProtection = true
*.lteB.useProtection = true
*.lteA.protectionSwitchTime = 0.5s
*.lteB.protectionSwitchTime = 0.5s
