[General]
network = p2pNetwork
sim-time-limit = 1s


[Config STM1]

*.lteA.stmLevel = 1
*.lteB.stmLevel = 1
*.lteA.numTributaries = 1
*.lteB.numTributaries = 1
**.packetSize= 780
**.packetInterval = 41.62 us

[Config STM4]

*.lteA.stmLevel = 4
*.lteB.stmLevel = 4
*.lteA.numTributaries = 1
*.lteB.numTributaries = 1
**.packetSize= 3120
**.packetInterval = 41.62 us

[Config STM16]

*.lteA.stmLevel = 16
*.lteB.stmLevel = 16
*.lteA.numTributaries = 1
*.lteB.numTributaries = 1
**.packetSize= 12480
**.packetInterval = 41.62 us

# Visualization and animation
*.visualizer.*.enabled = true
*.visualizer.*.animationSpeed = 20
*.visualizer.*.displayRoutes = false
*.visualizer.*.displayPacketDrops = true
*.visualizer.*.displayLabels = true

# Disable recording
**.scalar-recording = false
**.vector-recording = false

**.lteA.stmloadSTM.record = vector
**.lteB.stmloadSTM.record = vector

# Traffic generation
*.sourceA.packetInterval = 50us
*.sourceA.packetSize = 3000 # in bytes


[Protection]
*.lteA.useProtection = true
*.lteB.useProtection = true
*.lteA.protectionSwitchTime = 0.5s
*.lteB.protectionSwitchTime = 0.5s
